from django import forms
from .models import Servidor


class ServidorForm(forms.ModelForm):
    class Meta:
        model = Servidor
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'nome_pai': forms.TextInput(attrs={'class': 'form-control'}),
            'nome_mae': forms.TextInput(attrs={'class': 'form-control'}),
            'rg': forms.TextInput(attrs={'class': 'form-control'}),
            'orgao_emisso': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'endereco': forms.TextInput(attrs={'class': 'form-control'}),
            'num_reservista': forms.TextInput(attrs={'class': 'form-control'}),
            'orgao_emisso_reservista': forms.TextInput(attrs={'class': 'form-control'}),
            'numero_da_residencia': forms.TextInput(attrs={'class': 'form-control'}),
            'complemento_da_residencia': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'cidade': forms.TextInput(attrs={'class': 'form-control'}),
            'municipio_naturalizacao': forms.TextInput(attrs={'class': 'form-control'}),
            'titulo_eleitor': forms.TextInput(attrs={'class': 'form-control'}),
            'zona_eleitor': forms.TextInput(attrs={'class': 'form-control'}),
            'secao_eleitor': forms.TextInput(attrs={'class': 'form-control'}),
            'cidade_titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'num_habilitacao': forms.TextInput(attrs={'class': 'form-control'}),
            'cat_habilitacao': forms.TextInput(attrs={'class': 'form-control'}),
            'nome_empresa': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_sanguineo': forms.TextInput(attrs={'class': 'form-control'}),
            'fator_rh': forms.TextInput(attrs={'class': 'form-control'}),
            'num_rne': forms.TextInput(attrs={'class': 'form-control'}),
            'emissor_rne': forms.TextInput(attrs={'class': 'form-control'}),
            'clas_trabalho': forms.TextInput(attrs={'class': 'form-control'}),
            'ctps_n': forms.TextInput(attrs={'class': 'form-control'}),
            'serie_ctps': forms.TextInput(attrs={'class': 'form-control'}),
            'matricula': forms.TextInput(attrs={'class': 'form-control'}),
            'cargo': forms.TextInput(attrs={'class': 'form-control'}),
            'funcao': forms.TextInput(attrs={'class': 'form-control'}),
            'especialidade': forms.TextInput(attrs={'class': 'form-control'}),
            'nivel_salario': forms.TextInput(attrs={'class': 'form-control'}),
            'carga_horaria': forms.TextInput(attrs={'class': 'form-control'}),
            'banco': forms.TextInput(attrs={'class': 'form-control'}),
            'agencia': forms.TextInput(attrs={'class': 'form-control'}),
            'conta': forms.TextInput(attrs={'class': 'form-control'}),
            'estado_ctps': forms.Select(attrs={'class': 'form-control'}),
            'uf': forms.Select(attrs={'class': 'form-control'}),
            'uf_naturalizacao': forms.Select(attrs={'class': 'form-control'}),
            'estado_civil': forms.Select(attrs={'class': 'form-control'}),
            'raca': forms.Select(attrs={'class': 'form-control'}),
            'tipo_deficiencia': forms.Select(attrs={'class': 'form-control'}),
            'uf_reservista': forms.Select(attrs={'class': 'form-control'}),
            'uf_habilitacao': forms.Select(attrs={'class': 'form-control'}),
            'portador_pne': forms.Select(attrs={'class': 'form-control'}),
            'tipo_cargo': forms.Select(attrs={'class': 'form-control'}),
            'relacao_trabalho': forms.Select(attrs={'class': 'form-control'}),
            'regime_trabalho': forms.Select(attrs={'class': 'form-control'}),
            'tipo_vinculo': forms.Select(attrs={'class': 'form-control'}),
            'uf_rg': forms.Select(attrs={'class': 'form-control'}),
            'dt_nascimento': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_expedicao_rg': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_posse': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'ano_brasil': forms.TextInput(attrs={'class': 'form-control'}),
            'dt_admissao': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_desligamento': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_emissao_ctps': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_emissao_rne': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_final_emprego': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_emissao_titulo': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_naturalizacao': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_validade_habilitacao': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_primeiro_emprego': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_primeira_habilitacao': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'dt_emissao_reservista': forms.TextInput(attrs={'class': 'form-control mask-data'}),
            'tel_fixo': forms.TextInput(attrs={'class': 'form-control mask-fixo'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control mask-cpf'}),
            'cep': forms.TextInput(attrs={'class': 'form-control mask-cep'}),
            'tel_celular': forms.TextInput(attrs={'class': 'form-control mask-celular'}),
            'sexo': forms.Select(attrs={'class': 'form-control'}),
            'nascionalidade': forms.Select(attrs={'class': 'form-control'}),
        }

